Avoid an error in python 3.10
Avoid the

    ImportError: cannot import name 'Iterable' from 'collections'

error in python 3.10.  We may need to remove the expect part once
python 3.10 is fixed.